import { eventAssets } from './assetMap'
import type { EventDefinition } from './types'

export const eventDefinitions: EventDefinition[] = [
  {
    id: 'intro-start',
    title: '入学起步',
    description: '新的高中生活开始了。先稳住成绩，再为高考积累底气。',
    phase: 'highschool',
    image: eventAssets['event-intro-start'],
    unlockRequirements: [],
  },
  {
    id: 'monthly-exam',
    title: '第一次月考',
    description: '第一次阶段性检验已经到来。你开始意识到持续复习的重要性。',
    phase: 'highschool',
    image: eventAssets['event-monthly-exam'],
    unlockRequirements: ['phase:highschool', 'knowledge:35'],
    rewards: { reputation: 3 },
  },
  {
    id: 'mock-exam',
    title: '模拟考提醒',
    description: '模拟考成绩会直接影响心态。现在多做真题，正式考试会轻松很多。',
    phase: 'highschool',
    image: eventAssets['event-mock-exam'],
    unlockRequirements: ['phase:highschool', 'prep:30'],
    rewards: { reputation: 4 },
  },
  {
    id: 'entrance-exam-ready',
    title: '升学考试就绪',
    description: '知识与备考都达到了考试要求，正式进入高考阶段。',
    phase: 'exam',
    image: eventAssets['event-entrance-exam-ready'],
    unlockRequirements: ['phase:highschool', 'knowledge:85', 'prep:45'],
    nextPhase: 'exam',
  },
  {
    id: 'entrance-exam-forced',
    title: '高中阶段结束',
    description: '高中三年已经结束，不论准备是否充分，都要进入高考阶段。',
    phase: 'exam',
    image: eventAssets['event-entrance-exam-forced'],
    unlockRequirements: ['entranceExamForced:true'],
    nextPhase: 'exam',
  },
  {
    id: 'entrance-exam',
    title: '高考开始',
    description: '高考窗口已经开启。先打一局考试小游戏，再决定是否立刻参加。',
    phase: 'exam',
    image: eventAssets['event-entrance-exam'],
    unlockRequirements: ['phase:exam'],
  },
  {
    id: 'entrance-exam-pass',
    title: '高考通过',
    description: '你顺利通过高考，大学路线正式开启。',
    phase: 'college',
    image: eventAssets['event-exam-pass'],
    unlockRequirements: ['phase:exam', 'entranceExamTaken:true', 'entranceExamPassedState:true'],
    nextPhase: 'college',
    nextRoute: 'college',
    rewards: { reputation: 12, knowledge: 10 },
  },
  {
    id: 'entrance-exam-fail',
    title: '高考未通过',
    description: '这次没能通过高考，但生活不会停下。基础打工路线现在开始。',
    phase: 'work-basic',
    image: eventAssets['event-exam-fail'],
    unlockRequirements: ['phase:exam', 'entranceExamTaken:true', 'entranceExamPassedState:false'],
    nextPhase: 'work-basic',
    nextRoute: 'work',
  },
  {
    id: 'college-midterm',
    title: '大学中期评估',
    description: '专业课程推进顺利，中后期任务已经展开。',
    phase: 'college',
    image: eventAssets['event-college-midterm'],
    unlockRequirements: ['phase:college', 'task:college-class:5'],
    rewards: { reputation: 8 },
  },
  {
    id: 'college-graduate-excellent',
    title: '大学高标准毕业',
    description:
      '你以高评价完成大学阶段。主线大学会直接具备经营资格，通关后大学体验则转为大学毕业后工作。',
    phase: 'college',
    image: eventAssets['event-college-graduate-excellent'],
    unlockRequirements: ['phase:college', 'collegeScore:80', 'reputation:100'],
    rewards: { reputation: 18 },
  },
  {
    id: 'college-graduate-normal',
    title: '大学普通毕业',
    description: '四年大学阶段完成，你获得了毕业后的工作优势。',
    phase: 'work-advanced-college',
    image: eventAssets['event-college-graduate-normal'],
    unlockRequirements: ['phase:college', 'phaseMinutes:2880'],
    rewards: { reputation: 12 },
    nextPhase: 'work-advanced-college',
  },
  {
    id: 'work-promotion',
    title: '工作晋升',
    description: '稳定表现带来了更好的岗位与更可靠的资源积累。',
    phase: 'work-basic',
    image: eventAssets['event-work-promotion'],
    unlockRequirements: ['phase:work-basic', 'task:work-overtime:2'],
    rewards: { reputation: 20, money: 28 },
  },
  {
    id: 'adult-exam-eligible',
    title: '成考报名资格',
    description: '知识与资金都已满足报名条件，成人高考阶段开启。',
    phase: 'adult-exam',
    image: eventAssets['event-adult-exam-eligible'],
    unlockRequirements: ['phase:work-basic', 'knowledge:110', 'money:300'],
    nextPhase: 'adult-exam',
  },
  {
    id: 'adult-exam-start-mainline',
    title: '成人高考开始',
    description: '主线成考开始。通过后将进入边工边学阶段，未通过则回到基础打工。',
    phase: 'adult-exam',
    image: eventAssets['event-adult-exam-start-mainline'],
    unlockRequirements: [
      'phase:adult-exam',
      'adultExamEntryType:mainline',
      'adultExamTaken:false',
      'adultExamStartPromptShown:false',
    ],
  },
  {
    id: 'adult-exam-start-postgame',
    title: '通关后成人高考开始',
    description: '通关后的大学体验需要先通过成人高考。',
    phase: 'adult-exam',
    image: eventAssets['event-adult-exam-start-postgame'],
    unlockRequirements: [
      'phase:adult-exam',
      'adultExamEntryType:postgame',
      'adultExamTaken:false',
      'adultExamStartPromptShown:false',
    ],
  },
  {
    id: 'adult-exam-pass-mainline',
    title: '成考通过',
    description: '成人高考通过，你进入边工边学阶段。',
    phase: 'work-study',
    image: eventAssets['event-adult-exam-pass-mainline'],
    unlockRequirements: [
      'phase:adult-exam',
      'adultExamEntryType:mainline',
      'adultExamTaken:true',
      'adultExamPassedState:true',
    ],
    nextPhase: 'work-study',
  },
  {
    id: 'adult-exam-pass-postgame',
    title: '通关后成考通过',
    description: '成人高考通过，大学体验阶段开启。',
    phase: 'college',
    image: eventAssets['event-adult-exam-pass-postgame'],
    unlockRequirements: [
      'phase:adult-exam',
      'adultExamEntryType:postgame',
      'adultExamTaken:true',
      'adultExamPassedState:true',
    ],
    nextPhase: 'college',
    nextRoute: 'college',
  },
  {
    id: 'adult-exam-fail-mainline',
    title: '成考未通过',
    description: '这次成考没有通过，回到基础打工。一年后可再次报名。',
    phase: 'work-basic',
    image: eventAssets['event-adult-exam-fail-mainline'],
    unlockRequirements: [
      'phase:adult-exam',
      'adultExamEntryType:mainline',
      'adultExamTaken:true',
      'adultExamPassedState:false',
    ],
    nextPhase: 'work-basic',
  },
  {
    id: 'adult-exam-fail-postgame',
    title: '通关后成考未通过',
    description: '这次成考没有通过，先回到通关后的自由阶段。',
    phase: 'postgame',
    image: eventAssets['event-adult-exam-fail-postgame'],
    unlockRequirements: [
      'phase:adult-exam',
      'adultExamEntryType:postgame',
      'adultExamTaken:true',
      'adultExamPassedState:false',
    ],
    nextPhase: 'postgame',
  },
  {
    id: 'adult-college-graduate-high',
    title: '成考高标准毕业',
    description: '你在边工边学中拿到高标准毕业评价，进入更高收益的工作分支。',
    phase: 'work-advanced-adult-high',
    image: eventAssets['event-adult-college-graduate-high'],
    unlockRequirements: ['phase:work-study', 'adultCredits:120', 'knowledge:180', 'reputation:120'],
    rewards: { reputation: 16 },
    nextPhase: 'work-advanced-adult-high',
  },
  {
    id: 'adult-college-graduate-normal',
    title: '成考普通毕业',
    description: '边工边学阶段完成，你进入成考毕业后的工作分支。',
    phase: 'work-advanced-adult-normal',
    image: eventAssets['event-adult-college-graduate-normal'],
    unlockRequirements: ['phase:work-study', 'phaseMinutes:2880'],
    rewards: { reputation: 10 },
    nextPhase: 'work-advanced-adult-normal',
  },
  {
    id: 'business-qualify-work',
    title: '工作线经营资格',
    description: '基础打工积累到足够声望，经营阶段开启。',
    phase: 'business',
    image: eventAssets['event-business-qualify-work'],
    unlockRequirements: ['phase:work-basic', 'workPromotion:true', 'reputation:120'],
    nextPhase: 'business',
  },
  {
    id: 'business-qualify-college',
    title: '大学毕业后经营资格',
    description: '大学毕业后的资金与声望已满足经营条件。',
    phase: 'business',
    image: eventAssets['event-business-qualify-college'],
    unlockRequirements: ['phase:work-advanced-college', 'reputation:140', 'money:1800'],
    nextPhase: 'business',
  },
  {
    id: 'business-qualify-adult-high',
    title: '成考高标准经营资格',
    description: '成考高标准毕业后的职业积累已满足经营条件。',
    phase: 'business',
    image: eventAssets['event-business-qualify-adult-high'],
    unlockRequirements: ['phase:work-advanced-adult-high', 'reputation:150', 'money:2200'],
    nextPhase: 'business',
  },
  {
    id: 'business-qualify-adult-normal',
    title: '成考普通毕业经营资格',
    description: '成考毕业后的职业积累已满足经营条件。',
    phase: 'business',
    image: eventAssets['event-business-qualify-adult-normal'],
    unlockRequirements: ['phase:work-advanced-adult-normal', 'reputation:145', 'money:2100'],
    nextPhase: 'business',
  },
  {
    id: 'business-unlock',
    title: '经营阶段开启',
    description: '你已经具备进入经营阶段的资源与声望，新的长期循环打开了。',
    phase: 'business',
    image: eventAssets['event-business-unlock'],
    unlockRequirements: ['phase:business', 'businessReady:true'],
    nextPhase: 'business',
  },
  {
    id: 'wealth-clear-basic-work',
    title: '基础打工财富自由',
    description: '经过多年打拼，你终于实现财富自由。',
    phase: 'postgame',
    image: eventAssets['event-wealth-clear-basic-work'],
    unlockRequirements: ['phase:work-basic', 'wealthFreeTarget:true'],
    nextPhase: 'postgame',
  },
  {
    id: 'wealth-clear-work-study',
    title: '边工边学财富自由',
    description: '经过多年边工边学，你终于实现财富自由。',
    phase: 'postgame',
    image: eventAssets['event-wealth-clear-work-study'],
    unlockRequirements: ['phase:work-study', 'wealthFreeTarget:true'],
    nextPhase: 'postgame',
  },
  {
    id: 'wealth-clear-college-work',
    title: '大学毕业工作财富自由',
    description: '经过多年实干，你终于实现财富自由。',
    phase: 'postgame',
    image: eventAssets['event-wealth-clear-college-work'],
    unlockRequirements: ['phase:work-advanced-college', 'wealthFreeTarget:true'],
    nextPhase: 'postgame',
  },
  {
    id: 'wealth-clear-adult-high-work',
    title: '成考高标工作财富自由',
    description: '经过多年打拼与进修，你终于实现财富自由。',
    phase: 'postgame',
    image: eventAssets['event-wealth-clear-adult-high-work'],
    unlockRequirements: ['phase:work-advanced-adult-high', 'wealthFreeTarget:true'],
    nextPhase: 'postgame',
  },
  {
    id: 'wealth-clear-adult-normal-work',
    title: '成考毕业工作财富自由',
    description: '经过多年打拼与进修，你终于实现财富自由。',
    phase: 'postgame',
    image: eventAssets['event-wealth-clear-adult-normal-work'],
    unlockRequirements: ['phase:work-advanced-adult-normal', 'wealthFreeTarget:true'],
    nextPhase: 'postgame',
  },
  {
    id: 'wealth-clear-business',
    title: '经营财富自由',
    description: '通过多年经营，你终于实现财富自由。',
    phase: 'postgame',
    image: eventAssets['event-wealth-clear-business'],
    unlockRequirements: ['phase:business', 'wealthFreeTarget:true'],
    nextPhase: 'postgame',
  },
  {
    id: 'collection-shop-unlock',
    title: '衣橱商店开启',
    description: '主线通关后，未获得皮肤可以通过本地商店入手。',
    phase: 'postgame',
    image: eventAssets['event-collection-shop-unlock'],
    unlockRequirements: ['mainCleared:true'],
  },
]

export const eventMap = Object.fromEntries(eventDefinitions.map((event) => [event.id, event]))
