import { skinAssets } from './assetMap'
import type { SkinDefinition } from './types'

export const skinDefinitions: SkinDefinition[] = [
  {
    id: 'skin-hs-uniform-basic',
    name: '起步校服',
    phase: 'highschool',
    route: 'common',
    rarity: 'common',
    image: skinAssets['skin-hs-uniform-basic'],
    unlockType: 'story',
    unlockRequirement: 'event:intro-start',
    sourceLabel: '初始获得',
  },
  {
    id: 'skin-hs-casual-afterclass',
    name: '放学日常',
    phase: 'highschool',
    route: 'common',
    rarity: 'common',
    image: skinAssets['skin-hs-casual-afterclass'],
    unlockType: 'task',
    unlockRequirement: 'task:study-class:3',
    sourceLabel: '完成 3 次课堂专注',
  },
  {
    id: 'skin-hs-exam-sprint',
    name: '考前冲刺',
    phase: 'highschool',
    route: 'common',
    rarity: 'rare',
    image: skinAssets['skin-hs-exam-sprint'],
    unlockType: 'task',
    unlockRequirement: 'task:study-mock-exam:2',
    sourceLabel: '完成 2 次模拟考试',
  },
  {
    id: 'skin-hs-honor-award',
    name: '月考荣誉',
    phase: 'highschool',
    route: 'common',
    rarity: 'rare',
    image: skinAssets['skin-hs-honor-award'],
    unlockType: 'story',
    unlockRequirement: 'event:monthly-exam',
    sourceLabel: '触发第一次月考事件',
  },
  {
    id: 'skin-college-daily',
    name: '校园日常',
    phase: 'college',
    route: 'college',
    rarity: 'route',
    image: skinAssets['skin-college-daily'],
    unlockType: 'route',
    unlockRequirement: 'route:college',
    sourceLabel: '进入大学路线',
  },
  {
    id: 'skin-college-library',
    name: '图书馆自习',
    phase: 'college',
    route: 'college',
    rarity: 'common',
    image: skinAssets['skin-college-library'],
    unlockType: 'task',
    unlockRequirement: 'task:college-library:2',
    sourceLabel: '完成 2 次图书馆自习',
  },
  {
    id: 'skin-college-lab',
    name: '实验室白袍',
    phase: 'college',
    route: 'college',
    rarity: 'route',
    image: skinAssets['skin-college-lab'],
    unlockType: 'task',
    unlockRequirement: 'task:college-lab:2',
    sourceLabel: '完成 2 次实验室任务',
  },
  {
    id: 'skin-college-club',
    name: '社团骨干',
    phase: 'college',
    route: 'college',
    rarity: 'route',
    image: skinAssets['skin-college-club'],
    unlockType: 'task',
    unlockRequirement: 'task:college-thesis:2',
    sourceLabel: '完成 2 次小组项目',
  },
  {
    id: 'skin-college-competition',
    name: '竞赛主力',
    phase: 'college',
    route: 'college',
    rarity: 'route',
    image: skinAssets['skin-college-competition'],
    unlockType: 'story',
    unlockRequirement: 'event:college-midterm',
    sourceLabel: '触发大学中期评估',
  },
  {
    id: 'skin-work-apprentice',
    name: '初入职场',
    phase: 'work',
    route: 'work',
    rarity: 'route',
    image: skinAssets['skin-work-apprentice'],
    unlockType: 'route',
    unlockRequirement: 'route:work',
    sourceLabel: '进入打工路线',
  },
  {
    id: 'skin-work-store-uniform',
    name: '便利店制服',
    phase: 'work',
    route: 'work',
    rarity: 'common',
    image: skinAssets['skin-work-store-uniform'],
    unlockType: 'task',
    unlockRequirement: 'task:work-store:2',
    sourceLabel: '完成 2 次便利店值班',
  },
  {
    id: 'skin-work-restaurant',
    name: '餐厅服务生',
    phase: 'work',
    route: 'work',
    rarity: 'common',
    image: skinAssets['skin-work-restaurant'],
    unlockType: 'task',
    unlockRequirement: 'task:work-restaurant:2',
    sourceLabel: '完成 2 次餐厅服务',
  },
  {
    id: 'skin-work-delivery',
    name: '极速外送',
    phase: 'work',
    route: 'work',
    rarity: 'route',
    image: skinAssets['skin-work-delivery'],
    unlockType: 'task',
    unlockRequirement: 'task:work-delivery:2',
    sourceLabel: '完成 2 次外送跑单',
  },
  {
    id: 'skin-work-commuter',
    name: '通勤日常',
    phase: 'work',
    route: 'work',
    rarity: 'route',
    image: skinAssets['skin-work-commuter'],
    unlockType: 'story',
    unlockRequirement: 'event:work-promotion',
    sourceLabel: '触发工作晋升事件',
  },
  {
    id: 'skin-biz-manager',
    name: '团队经理',
    phase: 'business',
    route: 'business',
    rarity: 'route',
    image: skinAssets['skin-biz-manager'],
    unlockType: 'story',
    unlockRequirement: 'event:business-unlock',
    sourceLabel: '开启 business 阶段',
  },
  {
    id: 'skin-biz-founder',
    name: '创业者',
    phase: 'business',
    route: 'business',
    rarity: 'route',
    image: skinAssets['skin-biz-founder'],
    unlockType: 'task',
    unlockRequirement: 'task:biz-sales:3',
    sourceLabel: '完成 3 次拓展客户',
  },
  {
    id: 'skin-biz-award',
    name: '里程碑奖项',
    phase: 'business',
    route: 'business',
    rarity: 'route',
    image: skinAssets['skin-biz-award'],
    unlockType: 'story',
    unlockRequirement: 'mainCleared:true',
    sourceLabel: '完成主线通关',
  },
]

export const skinMap = Object.fromEntries(skinDefinitions.map((skin) => [skin.id, skin]))
