import type { TaskDefinition } from './types'

const REAL_SECONDS_PER_GAME_MINUTE = 4

const taskDurationMinutes: Record<string, number> = {
  'study-class': 45,
  'study-notes': 60,
  'study-review': 90,
  'study-mock-exam': 120,
  'club-activity': 70,
  'exam-last-review': 80,
  'recover-rest': 20,
  'college-class': 90,
  'college-library': 120,
  'college-lab': 150,
  'college-intern': 150,
  'college-thesis': 180,
  'college-competition': 210,
  'work-store': 60,
  'work-restaurant': 90,
  'work-delivery': 90,
  'work-training': 120,
  'work-overtime': 180,
  'night-selfstudy': 80,
  'adult-exam-review': 90,
  'ws-day-shift': 100,
  'ws-night-class': 100,
  'ws-weekend-project': 140,
  'ws-exam-prep': 120,
  'wc-pro-role': 120,
  'wc-team-lead': 150,
  'wc-industry-network': 140,
  'wah-skilled-role': 120,
  'wah-certificate-project': 150,
  'wah-career-upgrade': 170,
  'wan-skilled-role': 120,
  'wan-certificate-project': 150,
  'wan-career-upgrade': 170,
  'biz-orders': 120,
  'biz-team': 180,
  'biz-sales': 180,
  'biz-auto-profit': 240,
}

const sharedSprint = {
  sprintDurationSec: 10,
}

const baseTaskDefinitions: Array<Omit<TaskDefinition, 'durationMinutes'>> = [
  {
    id: 'study-class',
    name: '课堂专注',
    category: 'study',
    phase: ['highschool'],
    durationSec: 28,
    baseSuccessRate: 0.88,
    successRewards: { exp: 10, knowledge: 12 },
    failRewards: { exp: 4, knowledge: 5 },
    failPenaltySec: 5,
    sprintChargePerClick: 10,
    sprintProgressMultiplier: 1.8,
    sprintSuccessBonus: 0.06,
    affectedBySkills: ['study', 'focus'],
    unlockRequirements: [],
    backgroundId: 'bg-hs-classroom-day',
    description: '稳定积累知识，适合前期拉高考试底盘。',
    ...sharedSprint,
  },
  {
    id: 'study-notes',
    name: '整理笔记',
    category: 'exam-prep',
    phase: ['highschool'],
    durationSec: 34,
    baseSuccessRate: 0.84,
    successRewards: { exp: 12, knowledge: 14 },
    failRewards: { exp: 5, knowledge: 6 },
    failPenaltySec: 6,
    sprintChargePerClick: 11,
    sprintProgressMultiplier: 1.85,
    sprintSuccessBonus: 0.07,
    affectedBySkills: ['study', 'focus'],
    unlockRequirements: [],
    backgroundId: 'bg-hs-study-desk-night',
    description: '核心备考任务之一，会显著提升备考进度。',
    ...sharedSprint,
  },
  {
    id: 'study-review',
    name: '专题复习',
    category: 'exam-prep',
    phase: ['highschool'],
    durationSec: 40,
    baseSuccessRate: 0.8,
    successRewards: { exp: 14, knowledge: 18 },
    failRewards: { exp: 5, knowledge: 8 },
    failPenaltySec: 8,
    sprintChargePerClick: 12,
    sprintProgressMultiplier: 1.9,
    sprintSuccessBonus: 0.08,
    affectedBySkills: ['study', 'focus'],
    unlockRequirements: ['knowledge:20'],
    backgroundId: 'bg-hs-study-review',
    description: '中后段拉分任务，高知识收益与高备考成长。',
    ...sharedSprint,
  },
  {
    id: 'study-mock-exam',
    name: '模拟考试',
    category: 'exam-prep',
    phase: ['highschool'],
    durationSec: 46,
    baseSuccessRate: 0.78,
    successRewards: { exp: 16, knowledge: 20, reputation: 4 },
    failRewards: { exp: 6, knowledge: 8 },
    failPenaltySec: 10,
    sprintChargePerClick: 13,
    sprintProgressMultiplier: 2,
    sprintSuccessBonus: 0.1,
    affectedBySkills: ['study', 'focus', 'action'],
    unlockRequirements: ['knowledge:35'],
    backgroundId: 'bg-hs-exam-room',
    description: '模拟真实考试压力，失败率略高但收益最好。',
    ...sharedSprint,
  },
  {
    id: 'club-activity',
    name: '社团活动',
    category: 'study',
    phase: ['highschool'],
    durationSec: 42,
    baseSuccessRate: 0.84,
    successRewards: { exp: 12, knowledge: 5, reputation: 10 },
    failRewards: { exp: 5, knowledge: 2, reputation: 3 },
    failPenaltySec: 6,
    sprintChargePerClick: 10,
    sprintProgressMultiplier: 1.75,
    sprintSuccessBonus: 0.06,
    affectedBySkills: ['social', 'focus'],
    unlockRequirements: ['knowledge:15'],
    backgroundId: 'bg-hs-club-room',
    description: '平衡学习节奏，主要积累声望。',
    ...sharedSprint,
  },
  {
    id: 'exam-last-review',
    name: '考前冲刺',
    category: 'exam-prep',
    phase: ['exam'],
    durationSec: 48,
    baseSuccessRate: 0.82,
    successRewards: { exp: 16, knowledge: 18 },
    failRewards: { exp: 6, knowledge: 8 },
    failPenaltySec: 8,
    sprintChargePerClick: 12,
    sprintProgressMultiplier: 1.9,
    sprintSuccessBonus: 0.08,
    affectedBySkills: ['study', 'focus'],
    unlockRequirements: [],
    backgroundId: 'bg-exam-last-review',
    description: '考前最后复习，提升知识与备考状态。',
    ...sharedSprint,
  },
  {
    id: 'recover-rest',
    name: '短暂休整',
    category: 'recovery',
    phase: [
      'highschool',
      'exam',
      'college',
      'work-basic',
      'adult-exam',
      'work-study',
      'work-advanced-college',
      'work-advanced-adult-high',
      'work-advanced-adult-normal',
      'business',
    ],
    durationSec: 18,
    baseSuccessRate: 0.95,
    successRewards: { exp: 6 },
    failRewards: { exp: 2 },
    failPenaltySec: 2,
    sprintChargePerClick: 9,
    sprintProgressMultiplier: 1.6,
    sprintSuccessBonus: 0.03,
    affectedBySkills: ['focus'],
    unlockRequirements: [],
    backgroundId: 'bg-recover-rest',
    description: '低风险短任务，适合在任何阶段稳定过渡。',
    ...sharedSprint,
  },
  {
    id: 'college-class',
    name: '专业课程',
    category: 'campus',
    phase: ['college'],
    route: ['college'],
    durationSec: 44,
    baseSuccessRate: 0.86,
    successRewards: { exp: 18, knowledge: 22, reputation: 6 },
    failRewards: { exp: 8, knowledge: 9, reputation: 2 },
    failPenaltySec: 7,
    sprintChargePerClick: 11,
    sprintProgressMultiplier: 1.9,
    sprintSuccessBonus: 0.07,
    affectedBySkills: ['study', 'focus'],
    unlockRequirements: [],
    backgroundId: 'bg-college-campus',
    description: '大学阶段的基础成长任务，平衡知识与声望。',
    ...sharedSprint,
  },
  {
    id: 'college-library',
    name: '图书馆自习',
    category: 'campus',
    phase: ['college'],
    route: ['college'],
    durationSec: 50,
    baseSuccessRate: 0.84,
    successRewards: { exp: 20, knowledge: 26, reputation: 5 },
    failRewards: { exp: 8, knowledge: 10 },
    failPenaltySec: 8,
    sprintChargePerClick: 12,
    sprintProgressMultiplier: 2,
    sprintSuccessBonus: 0.08,
    affectedBySkills: ['study', 'focus', 'action'],
    unlockRequirements: ['task:college-class:2'],
    backgroundId: 'bg-college-library',
    description: '偏学术收益，适合快速堆高考试后半程优势。',
    ...sharedSprint,
  },
  {
    id: 'college-lab',
    name: '实验室任务',
    category: 'campus',
    phase: ['college'],
    route: ['college'],
    durationSec: 58,
    baseSuccessRate: 0.79,
    successRewards: { exp: 22, knowledge: 24, reputation: 10 },
    failRewards: { exp: 8, knowledge: 10, reputation: 3 },
    failPenaltySec: 10,
    sprintChargePerClick: 12,
    sprintProgressMultiplier: 2.05,
    sprintSuccessBonus: 0.09,
    affectedBySkills: ['study', 'focus', 'social'],
    unlockRequirements: ['task:college-class:3'],
    backgroundId: 'bg-college-lab',
    description: '更高声望收益，能更快靠近 business 门槛。',
    ...sharedSprint,
  },
  {
    id: 'college-intern',
    name: '企业实习',
    category: 'campus',
    phase: ['college'],
    route: ['college'],
    durationSec: 58,
    baseSuccessRate: 0.81,
    successRewards: { exp: 20, knowledge: 10, reputation: 14 },
    failRewards: { exp: 8, knowledge: 4, reputation: 5 },
    failPenaltySec: 10,
    sprintChargePerClick: 12,
    sprintProgressMultiplier: 2.02,
    sprintSuccessBonus: 0.09,
    affectedBySkills: ['study', 'social', 'focus'],
    unlockRequirements: ['task:college-library:2'],
    backgroundId: 'bg-biz-client-meeting',
    description: '大学就业准备任务，补充实践经验与声望。',
    ...sharedSprint,
  },
  {
    id: 'college-thesis',
    name: '毕设攻坚',
    category: 'campus',
    phase: ['college'],
    route: ['college'],
    durationSec: 60,
    baseSuccessRate: 0.77,
    successRewards: { exp: 20, reputation: 12 },
    failRewards: { exp: 8, reputation: 4 },
    failPenaltySec: 12,
    sprintChargePerClick: 13,
    sprintProgressMultiplier: 2.08,
    sprintSuccessBonus: 0.1,
    affectedBySkills: ['social', 'action', 'focus'],
    unlockRequirements: ['task:college-lab:2'],
    backgroundId: 'bg-college-project-room',
    description: '毕业关键任务，会提高大学评价分。',
    ...sharedSprint,
  },
  {
    id: 'college-competition',
    name: '竞赛冲刺',
    category: 'campus',
    phase: ['college'],
    route: ['college'],
    durationSec: 68,
    baseSuccessRate: 0.74,
    successRewards: { exp: 24, knowledge: 18, reputation: 16 },
    failRewards: { exp: 10, knowledge: 8, reputation: 6 },
    failPenaltySec: 14,
    sprintChargePerClick: 14,
    sprintProgressMultiplier: 2.12,
    sprintSuccessBonus: 0.12,
    affectedBySkills: ['study', 'social', 'action'],
    unlockRequirements: ['task:college-thesis:1'],
    backgroundId: 'bg-college-competition-hall',
    description: '大学路线关键任务，推进成果事件。',
    ...sharedSprint,
  },
  {
    id: 'work-store',
    name: '便利店值班',
    category: 'parttime',
    phase: ['work-basic'],
    route: ['work'],
    durationSec: 34,
    baseSuccessRate: 0.9,
    successRewards: { exp: 14, money: 24, reputation: 4 },
    failRewards: { exp: 6, money: 10, reputation: 1 },
    failPenaltySec: 5,
    sprintChargePerClick: 10,
    sprintProgressMultiplier: 1.8,
    sprintSuccessBonus: 0.06,
    affectedBySkills: ['social', 'focus'],
    unlockRequirements: [],
    backgroundId: 'bg-work-store',
    description: '稳定现金来源，是工作路线的起手任务。',
    ...sharedSprint,
  },
  {
    id: 'work-restaurant',
    name: '餐厅服务',
    category: 'parttime',
    phase: ['work-basic'],
    route: ['work'],
    durationSec: 42,
    baseSuccessRate: 0.85,
    successRewards: { exp: 16, money: 30, reputation: 6 },
    failRewards: { exp: 7, money: 12, reputation: 2 },
    failPenaltySec: 6,
    sprintChargePerClick: 11,
    sprintProgressMultiplier: 1.85,
    sprintSuccessBonus: 0.07,
    affectedBySkills: ['social', 'action'],
    unlockRequirements: ['task:work-store:2'],
    backgroundId: 'bg-work-restaurant',
    description: '更忙碌，但也带来更高的现金流。',
    ...sharedSprint,
  },
  {
    id: 'work-delivery',
    name: '外送跑单',
    category: 'work',
    phase: ['work-basic'],
    route: ['work'],
    durationSec: 40,
    baseSuccessRate: 0.83,
    successRewards: { exp: 16, money: 28, reputation: 7 },
    failRewards: { exp: 6, money: 12, reputation: 2 },
    failPenaltySec: 7,
    sprintChargePerClick: 11,
    sprintProgressMultiplier: 1.95,
    sprintSuccessBonus: 0.08,
    affectedBySkills: ['action', 'social'],
    unlockRequirements: ['task:work-store:2'],
    backgroundId: 'bg-work-delivery-street',
    description: '节奏更快，适合吃行动力和冲刺收益。',
    ...sharedSprint,
  },
  {
    id: 'work-training',
    name: '岗位培训',
    category: 'work',
    phase: ['work-basic'],
    route: ['work'],
    durationSec: 56,
    baseSuccessRate: 0.8,
    successRewards: { exp: 20, knowledge: 8, reputation: 13 },
    failRewards: { exp: 8, knowledge: 3, reputation: 4 },
    failPenaltySec: 9,
    sprintChargePerClick: 12,
    sprintProgressMultiplier: 2,
    sprintSuccessBonus: 0.09,
    affectedBySkills: ['focus', 'social'],
    unlockRequirements: ['task:work-restaurant:2'],
    backgroundId: 'bg-work-training-room',
    description: '提高职业跃迁速度，为 business 做准备。',
    ...sharedSprint,
  },
  {
    id: 'work-overtime',
    name: '加班冲业绩',
    category: 'work',
    phase: ['work-basic'],
    route: ['work'],
    durationSec: 62,
    baseSuccessRate: 0.76,
    successRewards: { exp: 22, money: 38, reputation: 17 },
    failRewards: { exp: 8, money: 16, reputation: 5 },
    failPenaltySec: 12,
    sprintChargePerClick: 14,
    sprintProgressMultiplier: 2.1,
    sprintSuccessBonus: 0.12,
    affectedBySkills: ['focus', 'action', 'social'],
    unlockRequirements: ['task:work-training:2'],
    backgroundId: 'bg-work-overtime-floor',
    description: '工作路线关键任务，收益高且会触发晋升。',
    ...sharedSprint,
  },
  {
    id: 'night-selfstudy',
    name: '夜间自学',
    category: 'exam-prep',
    phase: ['work-basic'],
    route: ['work'],
    durationSec: 48,
    baseSuccessRate: 0.82,
    successRewards: { exp: 12, knowledge: 18 },
    failRewards: { exp: 5, knowledge: 7 },
    failPenaltySec: 7,
    sprintChargePerClick: 11,
    sprintProgressMultiplier: 1.85,
    sprintSuccessBonus: 0.07,
    affectedBySkills: ['study', 'focus'],
    unlockRequirements: ['money:200'],
    backgroundId: 'bg-hs-night-desk',
    description: '工作后的自学任务，为成人高考做准备。',
    ...sharedSprint,
  },
  {
    id: 'adult-exam-review',
    name: '成考复习',
    category: 'exam-prep',
    phase: ['adult-exam'],
    durationSec: 54,
    baseSuccessRate: 0.82,
    successRewards: { exp: 16, knowledge: 18 },
    failRewards: { exp: 6, knowledge: 8 },
    failPenaltySec: 8,
    sprintChargePerClick: 12,
    sprintProgressMultiplier: 1.9,
    sprintSuccessBonus: 0.08,
    affectedBySkills: ['study', 'focus'],
    unlockRequirements: [],
    backgroundId: 'bg-adult-exam-review',
    description: '成人高考前复习，提升通过率。',
    ...sharedSprint,
  },
  {
    id: 'ws-day-shift',
    name: '白班工作',
    category: 'work',
    phase: ['work-study'],
    route: ['work'],
    durationSec: 60,
    baseSuccessRate: 0.82,
    successRewards: { exp: 16, money: 34, reputation: 4 },
    failRewards: { exp: 6, money: 12, reputation: 1 },
    failPenaltySec: 9,
    sprintChargePerClick: 11,
    sprintProgressMultiplier: 1.85,
    sprintSuccessBonus: 0.07,
    affectedBySkills: ['focus', 'social'],
    unlockRequirements: [],
    backgroundId: 'bg-adult-day-shift',
    description: '边工边学阶段的工作任务，收益低于全职打工。',
    ...sharedSprint,
  },
  {
    id: 'ws-night-class',
    name: '夜校课程',
    category: 'study',
    phase: ['work-study'],
    route: ['work'],
    durationSec: 60,
    baseSuccessRate: 0.8,
    successRewards: { exp: 16, knowledge: 20 },
    failRewards: { exp: 6, knowledge: 8 },
    failPenaltySec: 9,
    sprintChargePerClick: 11,
    sprintProgressMultiplier: 1.85,
    sprintSuccessBonus: 0.07,
    affectedBySkills: ['study', 'focus'],
    unlockRequirements: [],
    backgroundId: 'bg-adult-night-school',
    description: '边工边学阶段的课程任务，推进成考学分。',
    ...sharedSprint,
  },
  {
    id: 'ws-weekend-project',
    name: '周末实训',
    category: 'campus',
    phase: ['work-study'],
    route: ['work'],
    durationSec: 84,
    baseSuccessRate: 0.78,
    successRewards: { exp: 18, reputation: 12 },
    failRewards: { exp: 7, reputation: 4 },
    failPenaltySec: 12,
    sprintChargePerClick: 12,
    sprintProgressMultiplier: 1.95,
    sprintSuccessBonus: 0.08,
    affectedBySkills: ['study', 'social', 'focus'],
    unlockRequirements: ['task:ws-night-class:2'],
    backgroundId: 'bg-college-training-center',
    description: '边工边学毕业关键任务，推进成考学分与声望。',
    ...sharedSprint,
  },
  {
    id: 'ws-exam-prep',
    name: '成考复训',
    category: 'exam-prep',
    phase: ['work-study'],
    route: ['work'],
    durationSec: 72,
    baseSuccessRate: 0.77,
    successRewards: { exp: 18, knowledge: 16 },
    failRewards: { exp: 7, knowledge: 6 },
    failPenaltySec: 12,
    sprintChargePerClick: 12,
    sprintProgressMultiplier: 1.95,
    sprintSuccessBonus: 0.08,
    affectedBySkills: ['study', 'focus'],
    unlockRequirements: ['knowledge:140'],
    backgroundId: 'bg-adult-exam-retake',
    description: '边工边学毕业冲刺任务，推进成考学分。',
    ...sharedSprint,
  },
  {
    id: 'wc-pro-role',
    name: '专业岗位任职',
    category: 'work',
    phase: ['work-advanced-college'],
    route: ['college'],
    durationSec: 72,
    baseSuccessRate: 0.86,
    successRewards: { exp: 20, money: 70, reputation: 14 },
    failRewards: { exp: 8, money: 24, reputation: 5 },
    failPenaltySec: 9,
    sprintChargePerClick: 12,
    sprintProgressMultiplier: 1.95,
    sprintSuccessBonus: 0.08,
    affectedBySkills: ['social', 'focus'],
    unlockRequirements: ['graduatedCollege:true'],
    backgroundId: 'bg-adult-pro-office',
    description: '高考大学毕业后的高收益工作。',
    ...sharedSprint,
  },
  {
    id: 'wc-team-lead',
    name: '团队协作管理',
    category: 'work',
    phase: ['work-advanced-college'],
    route: ['college'],
    durationSec: 90,
    baseSuccessRate: 0.82,
    successRewards: { exp: 22, money: 82, reputation: 18 },
    failRewards: { exp: 9, money: 28, reputation: 6 },
    failPenaltySec: 11,
    sprintChargePerClick: 13,
    sprintProgressMultiplier: 2,
    sprintSuccessBonus: 0.09,
    affectedBySkills: ['social', 'action', 'focus'],
    unlockRequirements: ['task:wc-pro-role:2'],
    backgroundId: 'bg-adult-team-management',
    description: '大学毕业后工作路线的进阶任务。',
    ...sharedSprint,
  },
  {
    id: 'wc-industry-network',
    name: '行业拓展',
    category: 'work',
    phase: ['work-advanced-college'],
    route: ['college'],
    durationSec: 84,
    baseSuccessRate: 0.8,
    successRewards: { exp: 20, money: 62, reputation: 24 },
    failRewards: { exp: 8, money: 22, reputation: 8 },
    failPenaltySec: 11,
    sprintChargePerClick: 13,
    sprintProgressMultiplier: 2,
    sprintSuccessBonus: 0.09,
    affectedBySkills: ['social', 'business'],
    unlockRequirements: ['task:wc-team-lead:2'],
    backgroundId: 'bg-biz-networking-lounge',
    description: '积累行业资源，推动经营资格。',
    ...sharedSprint,
  },
  {
    id: 'wah-skilled-role',
    name: '技能岗位任职',
    category: 'work',
    phase: ['work-advanced-adult-high'],
    route: ['work'],
    durationSec: 72,
    baseSuccessRate: 0.84,
    successRewards: { exp: 18, money: 58, reputation: 12 },
    failRewards: { exp: 7, money: 20, reputation: 4 },
    failPenaltySec: 9,
    sprintChargePerClick: 12,
    sprintProgressMultiplier: 1.95,
    sprintSuccessBonus: 0.08,
    affectedBySkills: ['social', 'focus'],
    unlockRequirements: ['adultGraduationTier:high'],
    backgroundId: 'bg-adult-skill-desk',
    description: '成考高标准毕业后的中高收益岗位。',
    ...sharedSprint,
  },
  {
    id: 'wah-certificate-project',
    name: '证书项目实践',
    category: 'work',
    phase: ['work-advanced-adult-high'],
    route: ['work'],
    durationSec: 90,
    baseSuccessRate: 0.8,
    successRewards: { exp: 20, money: 66, reputation: 16 },
    failRewards: { exp: 8, money: 24, reputation: 5 },
    failPenaltySec: 11,
    sprintChargePerClick: 13,
    sprintProgressMultiplier: 2,
    sprintSuccessBonus: 0.09,
    affectedBySkills: ['social', 'action'],
    unlockRequirements: ['task:wah-skilled-role:2'],
    backgroundId: 'bg-adult-cert-lab',
    description: '证书实践带来更强职业收益。',
    ...sharedSprint,
  },
  {
    id: 'wah-career-upgrade',
    name: '岗位升级冲刺',
    category: 'work',
    phase: ['work-advanced-adult-high'],
    route: ['work'],
    durationSec: 102,
    baseSuccessRate: 0.78,
    successRewards: { exp: 22, money: 78, reputation: 20 },
    failRewards: { exp: 9, money: 28, reputation: 7 },
    failPenaltySec: 13,
    sprintChargePerClick: 13,
    sprintProgressMultiplier: 2.05,
    sprintSuccessBonus: 0.1,
    affectedBySkills: ['social', 'action', 'focus'],
    unlockRequirements: ['task:wah-certificate-project:2'],
    backgroundId: 'bg-adult-career-upgrade',
    description: '成考高标准毕业工作路线的高收益任务。',
    ...sharedSprint,
  },
  {
    id: 'wan-skilled-role',
    name: '技能岗位任职',
    category: 'work',
    phase: ['work-advanced-adult-normal'],
    route: ['work'],
    durationSec: 72,
    baseSuccessRate: 0.84,
    successRewards: { exp: 18, money: 48, reputation: 10 },
    failRewards: { exp: 7, money: 18, reputation: 4 },
    failPenaltySec: 9,
    sprintChargePerClick: 12,
    sprintProgressMultiplier: 1.95,
    sprintSuccessBonus: 0.08,
    affectedBySkills: ['social', 'focus'],
    unlockRequirements: ['adultGraduationTier:normal'],
    backgroundId: 'bg-adult-skill-lab',
    description: '成考普通毕业后的中等收益岗位。',
    ...sharedSprint,
  },
  {
    id: 'wan-certificate-project',
    name: '证书项目实践',
    category: 'work',
    phase: ['work-advanced-adult-normal'],
    route: ['work'],
    durationSec: 90,
    baseSuccessRate: 0.8,
    successRewards: { exp: 20, money: 56, reputation: 14 },
    failRewards: { exp: 8, money: 22, reputation: 5 },
    failPenaltySec: 11,
    sprintChargePerClick: 13,
    sprintProgressMultiplier: 2,
    sprintSuccessBonus: 0.09,
    affectedBySkills: ['social', 'action'],
    unlockRequirements: ['task:wan-skilled-role:2'],
    backgroundId: 'bg-adult-cert-office',
    description: '普通毕业后的职业进阶任务。',
    ...sharedSprint,
  },
  {
    id: 'wan-career-upgrade',
    name: '岗位升级冲刺',
    category: 'work',
    phase: ['work-advanced-adult-normal'],
    route: ['work'],
    durationSec: 102,
    baseSuccessRate: 0.78,
    successRewards: { exp: 22, money: 66, reputation: 18 },
    failRewards: { exp: 9, money: 24, reputation: 6 },
    failPenaltySec: 13,
    sprintChargePerClick: 13,
    sprintProgressMultiplier: 2.05,
    sprintSuccessBonus: 0.1,
    affectedBySkills: ['social', 'action', 'focus'],
    unlockRequirements: ['task:wan-certificate-project:2'],
    backgroundId: 'bg-adult-career-push',
    description: '成考普通毕业工作路线的高收益任务。',
    ...sharedSprint,
  },
  {
    id: 'biz-orders',
    name: '接项目',
    category: 'business',
    phase: ['business'],
    durationSec: 54,
    baseSuccessRate: 0.86,
    successRewards: { exp: 22, money: 48, reputation: 10 },
    failRewards: { exp: 8, money: 18, reputation: 4 },
    failPenaltySec: 8,
    sprintChargePerClick: 12,
    sprintProgressMultiplier: 1.95,
    sprintSuccessBonus: 0.08,
    affectedBySkills: ['business', 'social'],
    unlockRequirements: ['businessReady:true'],
    backgroundId: 'bg-biz-project-intake',
    description: '进入经营阶段后的基础现金流任务。',
    ...sharedSprint,
  },
  {
    id: 'biz-team',
    name: '管理团队',
    category: 'business',
    phase: ['business'],
    durationSec: 60,
    baseSuccessRate: 0.83,
    successRewards: { exp: 24, money: 44, reputation: 14 },
    failRewards: { exp: 10, money: 16, reputation: 5 },
    failPenaltySec: 10,
    sprintChargePerClick: 13,
    sprintProgressMultiplier: 2,
    sprintSuccessBonus: 0.09,
    affectedBySkills: ['business', 'social', 'focus'],
    unlockRequirements: ['task:biz-orders:2'],
    backgroundId: 'bg-biz-team-room',
    description: '提高声望成长，是通关节点的重要推动器。',
    ...sharedSprint,
  },
  {
    id: 'biz-sales',
    name: '拓展客户',
    category: 'business',
    phase: ['business'],
    durationSec: 64,
    baseSuccessRate: 0.8,
    successRewards: { exp: 22, money: 62, reputation: 16 },
    failRewards: { exp: 9, money: 24, reputation: 6 },
    failPenaltySec: 12,
    sprintChargePerClick: 13,
    sprintProgressMultiplier: 2.05,
    sprintSuccessBonus: 0.1,
    affectedBySkills: ['business', 'social', 'action'],
    unlockRequirements: ['task:biz-orders:2'],
    backgroundId: 'bg-biz-office',
    description: '商业阶段的核心赚钱任务。',
    ...sharedSprint,
  },
  {
    id: 'biz-auto-profit',
    name: '自动化收益',
    category: 'business',
    phase: ['business'],
    durationSec: 72,
    baseSuccessRate: 0.77,
    successRewards: { exp: 26, money: 82, reputation: 18 },
    failRewards: { exp: 10, money: 32, reputation: 7 },
    failPenaltySec: 14,
    sprintChargePerClick: 14,
    sprintProgressMultiplier: 2.12,
    sprintSuccessBonus: 0.11,
    affectedBySkills: ['business', 'focus', 'action'],
    unlockRequirements: ['task:biz-team:2', 'task:biz-sales:2'],
    backgroundId: 'bg-biz-rnd-studio',
    description: '高收益经营任务，适合在后期快速冲击财富自由目标。',
    ...sharedSprint,
  },
]

export const taskDefinitions: TaskDefinition[] = baseTaskDefinitions.map((task) => {
  const durationMinutes = taskDurationMinutes[task.id] ?? task.durationSec
  return {
    ...task,
    durationMinutes,
    durationSec: Math.round(durationMinutes * REAL_SECONDS_PER_GAME_MINUTE),
  }
})
