import type { CharacterData, ThemeConfig } from './types'

export const THEMES: ThemeConfig[] = [
  {
    id: 'urban',
    name: '都市',
    cardBackFallback: 'linear-gradient(135deg, #0a1628 0%, #1a3a5c 50%, #0a1628 100%)',
    accentColor: '#FF8A65',
    imageNames: [
      'ai-lian-na',
      'lin',
      'shi-zhi',
      'wei-wei-an',
      'tao-zi',
      'miao-jiang',
      'ling',
      'mei-ying',
      'lei-la',
      'xiao-kui',
      'jie-yi',
      'sa',
      'qing-zi',
      'ying',
      'qin-yin',
      'you-ya',
      'meng-meng',
      'xiang',
    ],
    characters: [
      { id: 1, title: '【极速幻影 · 艾莲娜】', name: '艾莲娜', rarity: 'SSR', imageIndex: 0 },
      { id: 2, title: '【绝对正义 · 凛】', name: '凛', rarity: 'SSR', imageIndex: 1 },
      { id: 3, title: '【午夜天籁 · 诗织】', name: '诗织', rarity: 'SSR', imageIndex: 2 },
      { id: 4, title: '【冷冽精英 · 薇薇安】', name: '薇薇安', rarity: 'SR', imageIndex: 3 },
      { id: 5, title: '【街头涂鸦 · 桃子】', name: '桃子', rarity: 'SR', imageIndex: 4 },
      { id: 6, title: '【猫咖奇遇 · 喵酱】', name: '喵酱', rarity: 'SR', imageIndex: 5 },
      { id: 7, title: '【午夜极客 · 零】', name: '零', rarity: 'SR', imageIndex: 6 },
      { id: 8, title: '【暗夜怪盗 · 魅影】', name: '魅影', rarity: 'SR', imageIndex: 7 },
      { id: 9, title: '【霓虹微醺 · 蕾拉】', name: '蕾拉', rarity: 'SR', imageIndex: 8 },
      { id: 10, title: '【元气外卖 · 小葵】', name: '小葵', rarity: 'R', imageIndex: 9 },
      { id: 11, title: '【便利店长 · 结衣】', name: '结衣', rarity: 'R', imageIndex: 10 },
      { id: 12, title: '【疾风快递 · 飒】', name: '飒', rarity: 'R', imageIndex: 11 },
      { id: 13, title: '【晨曦慢跑 · 晴子】', name: '晴子', rarity: 'R', imageIndex: 12 },
      { id: 14, title: '【高校JK · 樱】', name: '樱', rarity: 'R', imageIndex: 13 },
      { id: 15, title: '【流浪乐手 · 琴音】', name: '琴音', rarity: 'R', imageIndex: 14 },
      { id: 16, title: '【知性主编 · 优雅】', name: '优雅', rarity: 'R', imageIndex: 15 },
      { id: 17, title: '【爱心兽医 · 萌萌】', name: '萌萌', rarity: 'R', imageIndex: 16 },
      { id: 18, title: '【街头DJ · 响】', name: '响', rarity: 'R', imageIndex: 17 },
    ],
  },
  {
    id: 'ancient',
    name: '古风',
    cardBackFallback: 'linear-gradient(135deg, #1a0a2e 0%, #3a1a5c 50%, #1a0a2e 100%)',
    accentColor: '#7E57C2',
    imageNames: [
      'fei-yuan',
      'heng-e',
      'mu-lan',
      'miao-yin',
      'ling-lan',
      'zhang-gui',
      'shu-ya',
      'ling-er',
      'xi-zi',
      'qiao-er',
      'cui-cui',
      'zhi-yue',
      'jiu-mei',
      'shi-shi',
      'xi-er',
      'xiu-niang',
      'han-xiang',
      'chun-chun',
    ],
    characters: [
      { id: 19, title: '【落樱剑豪 · 绯鸢】', name: '绯鸢', rarity: 'SSR', imageIndex: 0 },
      { id: 20, title: '【广寒霓裳 · 姮娥】', name: '姮娥', rarity: 'SSR', imageIndex: 1 },
      { id: 21, title: '【烽火长歌 · 穆兰】', name: '穆兰', rarity: 'SSR', imageIndex: 2 },
      { id: 22, title: '【青莲琴瑟 · 妙音】', name: '妙音', rarity: 'SR', imageIndex: 3 },
      { id: 23, title: '【赤焰祭司 · 铃兰】', name: '铃兰', rarity: 'SR', imageIndex: 4 },
      { id: 24, title: '【浮生客栈 · 掌柜】', name: '掌柜', rarity: 'SR', imageIndex: 5 },
      { id: 25, title: '【墨染千秋 · 书雅】', name: '书雅', rarity: 'SR', imageIndex: 6 },
      { id: 26, title: '【百草医圣 · 灵儿】', name: '灵儿', rarity: 'SR', imageIndex: 7 },
      { id: 27, title: '【影舞幽伶 · 戏子】', name: '戏子', rarity: 'SR', imageIndex: 8 },
      { id: 28, title: '【提灯红娘 · 巧儿】', name: '巧儿', rarity: 'R', imageIndex: 9 },
      { id: 29, title: '【采茶山歌 · 翠翠】', name: '翠翠', rarity: 'R', imageIndex: 10 },
      { id: 30, title: '【江南织女 · 织月】', name: '织月', rarity: 'R', imageIndex: 11 },
      { id: 31, title: '【桃花釀 · 酒妹】', name: '酒妹', rarity: 'R', imageIndex: 12 },
      { id: 32, title: '【纸鸢寄情 · 诗诗】', name: '诗诗', rarity: 'R', imageIndex: 13 },
      { id: 33, title: '【弄潮捕鱼 · 溪儿】', name: '溪儿', rarity: 'R', imageIndex: 14 },
      { id: 34, title: '【刺绣玲珑 · 绣娘】', name: '绣娘', rarity: 'R', imageIndex: 15 },
      { id: 35, title: '【踏雪寻梅 · 寒香】', name: '寒香', rarity: 'R', imageIndex: 16 },
      { id: 36, title: '【团扇扑蝶 · 纯纯】', name: '纯纯', rarity: 'R', imageIndex: 17 },
    ],
  },
  {
    id: 'magic',
    name: '魔法',
    cardBackFallback: 'linear-gradient(135deg, #0a1a2e 0%, #1a3a6e 50%, #0a1a2e 100%)',
    accentColor: '#29B6F6',
    imageNames: [
      'lu-bi',
      'sai-la-si',
      'sheng-nv',
      'li-li-si',
      'nuo-ya',
      'ai-lin',
      'ai-er-sha',
      'shan-shan',
      'ti-xian',
      'jian-xi',
      'ni-ke',
      'ya-ya',
      'shu-ge',
      'ke-ke',
      'pai-niang',
      'chu-niang',
      'pao-pao',
      'tie-lv',
    ],
    characters: [
      { id: 37, title: '【红莲禁咒 · 露比】', name: '露比', rarity: 'SSR', imageIndex: 0 },
      { id: 38, title: '【星轨占卜 · 塞拉斯】', name: '塞拉斯', rarity: 'SSR', imageIndex: 1 },
      { id: 39, title: '【神圣治愈 · 圣女】', name: '圣女', rarity: 'SSR', imageIndex: 2 },
      { id: 40, title: '【影咒学者 · 莉莉丝】', name: '莉莉丝', rarity: 'SR', imageIndex: 3 },
      { id: 41, title: '【药剂天才 · 诺亚】', name: '诺亚', rarity: 'SR', imageIndex: 4 },
      { id: 42, title: '【绿野仙踪 · 艾琳】', name: '艾琳', rarity: 'SR', imageIndex: 5 },
      { id: 43, title: '【冰晶结界 · 艾尔莎】', name: '艾尔莎', rarity: 'SR', imageIndex: 6 },
      { id: 44, title: '【雷霆驭手 · 闪闪】', name: '闪闪', rarity: 'SR', imageIndex: 7 },
      { id: 45, title: '【构装人偶 · 提线】', name: '提线', rarity: 'SR', imageIndex: 8 },
      { id: 46, title: '【扫帚飞车 · 见习】', name: '见习', rarity: 'R', imageIndex: 9 },
      { id: 47, title: '【猫咪使模 · 妮可】', name: '妮可', rarity: 'R', imageIndex: 10 },
      { id: 48, title: '【植物共鸣 · 芽芽】', name: '芽芽', rarity: 'R', imageIndex: 11 },
      { id: 49, title: '【图书馆理 · 书阁】', name: '书阁', rarity: 'R', imageIndex: 12 },
      { id: 50, title: '【符文雕刻 · 刻刻】', name: '刻刻', rarity: 'R', imageIndex: 13 },
      { id: 51, title: '【占卜塔罗 · 牌娘】', name: '牌娘', rarity: 'R', imageIndex: 14 },
      { id: 52, title: '【魔法料理 · 厨娘】', name: '厨娘', rarity: 'R', imageIndex: 15 },
      { id: 53, title: '【元素精灵 · 泡泡】', name: '泡泡', rarity: 'R', imageIndex: 16 },
      { id: 54, title: '【学院风纪 · 铁律】', name: '铁律', rarity: 'R', imageIndex: 17 },
    ],
  },
  {
    id: 'fairytale',
    name: '童话',
    cardBackFallback: 'linear-gradient(135deg, #2a0a1e 0%, #5c1a3a 50%, #2a0a1e 100%)',
    accentColor: '#EC407A',
    imageNames: [
      'hong-mao',
      'li-si',
      'bai-xue',
      'se-lin',
      'xin-de-rui',
      'le-pei',
      'lu-ka',
      'tao-le-si',
      'ao-dai',
      'ge-rui-te',
      'yu-er',
      'min-gan',
      'juan-juan',
      'jun-zhang',
      'mian-mian',
      'hua-xian',
      'lin-da',
      'di-yin',
    ],
    characters: [
      { id: 55, title: '【逆袭猎手 · 红帽】', name: '红帽', rarity: 'SSR', imageIndex: 0 },
      { id: 56, title: '【时空异客 · 丽丝】', name: '丽丝', rarity: 'SSR', imageIndex: 1 },
      { id: 57, title: '【永夜黑化 · 白雪】', name: '白雪', rarity: 'SSR', imageIndex: 2 },
      { id: 58, title: '【幽海人鱼 · 瑟琳】', name: '瑟琳', rarity: 'SR', imageIndex: 3 },
      { id: 59, title: '【午夜灰烬 · 辛德瑞】', name: '辛德瑞', rarity: 'SR', imageIndex: 4 },
      { id: 60, title: '【发丝囚笼 · 乐佩】', name: '乐佩', rarity: 'SR', imageIndex: 5 },
      { id: 61, title: '【火柴微光 · 露卡】', name: '露卡', rarity: 'SR', imageIndex: 6 },
      { id: 62, title: '【红心暴君 · 桃乐丝】', name: '桃乐丝', rarity: 'SR', imageIndex: 7 },
      { id: 63, title: '【天鹅绝响 · 奥黛】', name: '奥黛', rarity: 'SR', imageIndex: 8 },
      { id: 64, title: '【面包屑引 · Gretel】', name: 'Gretel', rarity: 'R', imageIndex: 9 },
      { id: 65, title: '【丑小鸭拟 · 羽儿】', name: '羽儿', rarity: 'R', imageIndex: 10 },
      { id: 66, title: '【豌豆难眠 · 敏感】', name: '敏感', rarity: 'R', imageIndex: 11 },
      { id: 67, title: '【金发熊抱 · 卷卷】', name: '卷卷', rarity: 'R', imageIndex: 12 },
      { id: 68, title: '【胡桃夹子 · 军长】', name: '军长', rarity: 'R', imageIndex: 13 },
      { id: 69, title: '【睡美人懒 · 眠眠】', name: '眠眠', rarity: 'R', imageIndex: 14 },
      { id: 70, title: '【拇指姑娘 · 花仙】', name: '花仙', rarity: 'R', imageIndex: 15 },
      { id: 71, title: '【卖花姑娘 · 琳达】', name: '琳达', rarity: 'R', imageIndex: 16 },
      { id: 72, title: '【吹笛猎人 · 笛音】', name: '笛音', rarity: 'R', imageIndex: 17 },
    ],
  },
  {
    id: 'scifi',
    name: '科幻',
    cardBackFallback: 'linear-gradient(135deg, #0a1a2a 0%, #0a3a5a 50%, #0a1a2a 100%)',
    accentColor: '#00BCD4',
    imageNames: [
      'kai-se-lin',
      'ling-hao',
      'mi-sai-ya',
      'ai-li',
      'zhi-ji',
      'miao-wu',
      'lei-na',
      'ai-mi',
      'chu-yin',
      'luo-si',
      'lei-ya',
      'wei-te',
      'lv-yin',
      'hui-zi',
      'tie-quan',
      'feng-niao',
      'lin',
      'xiao-xiao',
    ],
    characters: [
      { id: 73, title: '【第一序列 · 凯瑟琳】', name: '凯瑟琳', rarity: 'SSR', imageIndex: 0 },
      { id: 74, title: '【虚空幽灵 · 零号】', name: '零号', rarity: 'SSR', imageIndex: 1 },
      { id: 75, title: '【天体AI · 弥赛亚】', name: '弥赛亚', rarity: 'SSR', imageIndex: 2 },
      { id: 76, title: '【机械重组 · 艾莉】', name: '艾莉', rarity: 'SR', imageIndex: 3 },
      { id: 77, title: '【量子跃迁 · 织姬】', name: '织姬', rarity: 'SR', imageIndex: 4 },
      { id: 78, title: '【星际游商 · 喵呜】', name: '喵呜', rarity: 'SR', imageIndex: 5 },
      { id: 79, title: '【机甲先锋 · 蕾娜】', name: '蕾娜', rarity: 'SR', imageIndex: 6 },
      { id: 80, title: '【异星学者 · 艾米】', name: '艾米', rarity: 'SR', imageIndex: 7 },
      { id: 81, title: '【银河偶像 · 初音】', name: '初音', rarity: 'SR', imageIndex: 8 },
      { id: 82, title: '【太空维修 · 螺丝】', name: '螺丝', rarity: 'R', imageIndex: 9 },
      { id: 83, title: '【星舰领航 · 蕾雅】', name: '蕾雅', rarity: 'R', imageIndex: 10 },
      { id: 84, title: '【舱内总管 · 维特】', name: '维特', rarity: 'R', imageIndex: 11 },
      { id: 85, title: '【基地园艺 · 绿茵】', name: '绿茵', rarity: 'R', imageIndex: 12 },
      { id: 86, title: '【数据分析 · 慧子】', name: '慧子', rarity: 'R', imageIndex: 13 },
      { id: 87, title: '【近地防卫 · 铁拳】', name: '铁拳', rarity: 'R', imageIndex: 14 },
      { id: 88, title: '【无人机控 · 蜂鸟】', name: '蜂鸟', rarity: 'R', imageIndex: 15 },
      { id: 89, title: '【星际留学生 · 琳】', name: '琳', rarity: 'R', imageIndex: 16 },
      { id: 90, title: '【冷冻舱唤 · 晓晓】', name: '晓晓', rarity: 'R', imageIndex: 17 },
    ],
  },
  {
    id: 'steam',
    name: '蒸汽',
    cardBackFallback: 'linear-gradient(135deg, #1a0a08 0%, #3a1a10 50%, #1a0a08 100%)',
    accentColor: '#8D6E63',
    imageNames: [
      'wa-te',
      'kai-li',
      'mi-yin',
      'fei-ao-na',
      'ma-li',
      'wei-duo',
      'tie-xin',
      'xie-er',
      'ge-zi',
      'tan-tan',
      'sha-sha',
      'biao-mei',
      'tian-xin',
      'run-hua',
      'mai-xiang',
      'shi-guang',
      'zhen-xian',
      'hu-hu',
    ],
    characters: [
      { id: 91, title: '【轰鸣重炮 · 瓦特】', name: '瓦特', rarity: 'SSR', imageIndex: 0 },
      { id: 92, title: '【微风飞艇 · 凯莉】', name: '凯莉', rarity: 'SSR', imageIndex: 1 },
      { id: 93, title: '【永动发条 · 秘银】', name: '秘银', rarity: 'SSR', imageIndex: 2 },
      { id: 94, title: '【高空滑翔 · 菲奥娜】', name: '菲奥娜', rarity: 'SR', imageIndex: 3 },
      { id: 95, title: '【发条护士 · 玛丽】', name: '玛丽', rarity: 'SR', imageIndex: 4 },
      { id: 96, title: '【皇家铁骑 · 维多】', name: '维多', rarity: 'SR', imageIndex: 5 },
      { id: 97, title: '【地下矿主 · 铁心】', name: '铁心', rarity: 'SR', imageIndex: 6 },
      { id: 98, title: '【雾都侦探 · 歇尔】', name: '歇尔', rarity: 'SR', imageIndex: 7 },
      { id: 99, title: '【飞空邮差 · 鸽子】', name: '鸽子', rarity: 'SR', imageIndex: 8 },
      { id: 100, title: '【锅炉工匠 · 炭炭】', name: '炭炭', rarity: 'R', imageIndex: 9 },
      { id: 101, title: '【齿轮打磨 · 砂砂】', name: '砂砂', rarity: 'R', imageIndex: 10 },
      { id: 102, title: '【气压监测 · 表妹】', name: '表妹', rarity: 'R', imageIndex: 11 },
      { id: 103, title: '【飞艇乘务 · 甜心】', name: '甜心', rarity: 'R', imageIndex: 12 },
      { id: 104, title: '【油污小猫 · 润滑】', name: '润滑', rarity: 'R', imageIndex: 13 },
      { id: 105, title: '【酒馆百灵 · 麦香】', name: '麦香', rarity: 'R', imageIndex: 14 },
      { id: 106, title: '【钟楼守护 · 时光】', name: '时光', rarity: 'R', imageIndex: 15 },
      { id: 107, title: '【皮革缝纫 · 针线】', name: '针线', rarity: 'R', imageIndex: 16 },
      { id: 108, title: '【街头卖报 · 呼呼】', name: '呼呼', rarity: 'R', imageIndex: 17 },
    ],
  },
]

export const DEFAULT_THEME_ID = 'urban'
export const DEFAULT_DIFFICULTY = 'easy'

export const THEME_ORDER = ['urban', 'ancient', 'magic', 'fairytale', 'steam', 'scifi'] as const

export function getThemeById(id: string): ThemeConfig | undefined {
  return THEMES.find((t) => t.id === id)
}

export function getCharacterById(
  id: number
): { theme: ThemeConfig; char: CharacterData } | undefined {
  for (const theme of THEMES) {
    const char = theme.characters.find((c) => c.id === id)
    if (char) return { theme, char }
  }
  return undefined
}

export function getCharactersByRarity(theme: ThemeConfig, rarity: string): CharacterData[] {
  return theme.characters.filter((c) => c.rarity === rarity)
}
