import type { DifficultyConfig, ThemeConfig, Difficulty } from './types'

export const DIFFICULTIES: Record<Difficulty, DifficultyConfig> = {
  easy: {
    label: '简单',
    pairs: 8,
    cols: 4,
  },
  normal: {
    label: '普通',
    pairs: 10,
    cols: 4,
  },
  hard: {
    label: '困难',
    pairs: 12,
    cols: 4,
  },
}

export const THEMES: ThemeConfig[] = [
  {
    id: 'animals',
    name: '动物乐园',
    cardBackFallback: 'linear-gradient(135deg, #F5E6D3 0%, #EDD9C4 50%, #F5E6D3 100%)',
    cardBackImage: 'animals.png',
    accentColor: '#D4A574',
    backgroundImage: 'bg-animals.png',
    imageNames: [
      'cat',
      'dog',
      'rabbit',
      'bear',
      'fox',
      'panda',
      'koala',
      'tiger',
      'lion',
      'frog',
      'pig',
      'chick',
    ],
  },
  {
    id: 'desserts',
    name: '甜蜜工坊',
    cardBackFallback: 'linear-gradient(135deg, #FCE4EC 0%, #F8BBD0 50%, #FCE4EC 100%)',
    cardBackImage: 'desserts.png',
    accentColor: '#EC407A',
    backgroundImage: 'bg-desserts.png',
    imageNames: [
      'cake',
      'chocolate',
      'cookie',
      'croissant',
      'cupcake',
      'donut',
      'ice-cream',
      'lollipop',
      'macaron',
      'marshmallow',
      'pie',
      'pudding',
    ],
  },
  {
    id: 'stars',
    name: '梦幻星空',
    cardBackFallback: 'linear-gradient(135deg, #E8EAF6 0%, #C5CAE9 50%, #E8EAF6 100%)',
    cardBackImage: 'stars.png',
    accentColor: '#5C6BC0',
    backgroundImage: 'bg-stars.png',
    imageNames: [
      'sun',
      'moon',
      'mercury',
      'venus',
      'earth',
      'mars',
      'jupiter',
      'saturn',
      'uranus',
      'neptune',
      'pluto',
      'comet',
    ],
  },
  {
    id: 'ocean',
    name: '海洋世界',
    cardBackFallback: 'linear-gradient(135deg, #E3F2FD 0%, #B2DFDB 50%, #E3F2FD 100%)',
    cardBackImage: 'ocean.png',
    accentColor: '#26A69A',
    backgroundImage: 'bg-ocean.png',
    imageNames: [
      'octopus',
      'crab',
      'fish',
      'shrimp',
      'squid',
      'pufferfish',
      'seashell',
      'lobster',
      'dolphin',
      'seal',
      'jellyfish',
      'starfish',
    ],
  },
  {
    id: 'plants',
    name: '植物花园',
    cardBackFallback: 'linear-gradient(135deg, #E8F5E9 0%, #C8E6C9 50%, #E8F5E9 100%)',
    cardBackImage: 'plants.png',
    accentColor: '#66BB6A',
    backgroundImage: 'bg-plants.png',
    imageNames: [
      'sunflower',
      'rose',
      'tulip',
      'lotus',
      'morning-glory',
      'dandelion',
      'lily',
      'lily-valley',
      'hydrangea',
      'orchid',
      'daffodil',
      'cockscomb',
    ],
  },
  {
    id: 'magic',
    name: '奇幻魔法',
    cardBackFallback: 'linear-gradient(135deg, #EDE7F6 0%, #E1BEE7 50%, #EDE7F6 100%)',
    cardBackImage: 'magic.png',
    accentColor: '#7E57C2',
    backgroundImage: 'bg-magic.png',
    imageNames: [
      'wizard-hat',
      'magic-wand',
      'crystal-ball',
      'spell-book',
      'potion',
      'magic-candle',
      'magic-key',
      'magic-mirror',
      'magic-ring',
      'magic-feather',
      'magic-gem',
      'magic-broom',
    ],
  },
]

export const DEFAULT_THEME_ID = 'animals'
export const DEFAULT_DIFFICULTY: Difficulty = 'easy'
